# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c2ebf6652e743927b799411433d0faa4"
name = "project-app2"
handle = "project-app2"
application_url = "https://vertex-ownership-partially-gradually.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "bohui-test2.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://vertex-ownership-partially-gradually.trycloudflare.com/auth/callback",
  "https://vertex-ownership-partially-gradually.trycloudflare.com/auth/shopify/callback",
  "https://vertex-ownership-partially-gradually.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
